### ISSUE TITLE
Push request fails pytest

### ISSUE THREAD

**Issue by MattLiangYH** [beam-tracing/Scotty#130]
Hi Peter

I created a new branch from the master branch, named [binorm_vec_test](https://github.com/beam-tracing/Scotty/tree/binorm_vec_test),  to edit one line in the analysis.py file as shown below:
![Screenshot 2024-07-01 142728](https://github.com/beam-tracing/Scotty/assets/35369782/eb2e8458-f931-432d-9eea-72c14295e766)

Then, I did a push request. However, the pytest on GItHub is currently giving this strange error:
![Screenshot 2024-07-01 142555](https://github.com/beam-tracing/Scotty/assets/35369782/2a9e10d1-6c6a-4ea3-9ffa-69eff482ada7)

However, my changes should not be causing this problem. Furthermore, I ran pytest internally on my computer and it managed to pass all the tests. Do you know how to solve this issue?

**Comment by ZedThree** [comment]
Hi @MattLiangYH, I can reproduce this in a fresh virtualenv on `master`, so it's definitely not your changes. It looks like it's related to the change in version of `netCDF4` -- the tests pass with 1.6.5 and fail with 1.7.1
