### ISSUE TITLE
Large files removed from history

### ISSUE THREAD

**Issue by ZedThree** [beam-tracing/Scotty#28]
I've used the [BFG repo cleaner](https://rtyley.github.io/bfg-repo-cleaner/) to remove lots of large files from the repo history. This means clones should take up much less disk space (from ~800MB to 45MB). Unfortunately, this involved rewriting history, so lots of commit hashes have changed. This will affect anyone who has branches or made local modifications to Scotty.

The easiest way to bring in these changes is to run:

```
$ git pull --rebase
Successfully rebased and updated refs/heads/master.
```
which will pull the cleaned commits and rebase and local changes on top of them.

For reference, if you try just `git pull`, you'll see and error message like: `fatal: Not possible to fast-forward, aborting.` This is expected, and you'll need the `--rebase` flag.

To update other branches, you'll need to run:

```
$ git switch master
$ git pull --rebase
$ git switch <branch>
$ git rebase master
```

If that fails for any reason, assuming your branches are otherwise up to date, you can run:

```
$ git switch master
$ git reset --hard origin/master
```

You should also be able to reduce the size of your cloned repo on disk by running:

```
git reflog expire --expire=now --all && git gc --prune=now --aggressive
```

This might take a few minutes to run, but should free up lots of disk space.

**Comment by valerian-chen** [comment]
No one has had any issue with this since @ZedThree's changes, closing this thread now.
