### ISSUE TITLE
Automate publishing on PyPI

### ISSUE THREAD

**Issue by ZedThree** [beam-tracing/Scotty#66]

**Comment by ZedThree** [comment]
We need a name for the package that users will give to `pip install <package name>`.
There are already a couple of packages with variations on "scotty": https://pypi.org/search/?q=scotty

Maybe one of:

- `beam-tracing-scotty`/`scotty-beam-tracing`
- `beam-me-up`/`beammeup`

**Comment by valerian-chen** [comment]
How about just 'beam-tracing'?

**Comment by ZedThree** [comment]
`scotty-beam-tracing`? It's a bit unfortunate that we can't have the package and module name be the same, but this variation is maybe the least surprising?

**Comment by valerian-chen** [comment]
Hey @ZedThree, what's the status with this?

**Comment by valerian-chen** [comment]
I'm afraid I've not, I have an irrational fear that I'll botch something up. Yeah, that sounds great, thank you so much!
