### ISSUE TITLE
Cannot pip install scotty on ``freia``

### ISSUE THREAD

**Issue by quinntpratt** [beam-tracing/Scotty#73]
Hi all, 
I made a local clone of scotty on freia via, 
`` git clone git@github.com:valerian-chen/Scotty.git SCOTTY``
then I went into the SCOTTY folder and did, 
``pip install .``
and I received the following error, 
```
Directory '.' is not installable. File 'setup.py' not found.
/usr/local/depot/Python-2.7.5/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

```

Upon further inspection it does appear that there's no ``setup.py`` file in the scotty repo. 
Thanks.

**Comment by ZedThree** [comment]
Ah, your `pip` is pointing to a version using python 2.7, which is no longer supported. Try using `python3 -m pip install .` instead.

Yes, `pip` should install all the required dependencies for you

**Comment by quinntpratt** [comment]
Yep, that fixed it.
I had to invoke the usual freia omfit recipe of loading/unloading modules to get the proper python3 path. 
After that pip worked and it installed the freegs module.
