### ISSUE TITLE
Launch angle conventions?

### ISSUE THREAD

**Issue by ZedThree** [beam-tracing/Scotty#75]
What are the conventions for the antenna launch angles? I know that they are given in degrees, and I'm reasonably sure that the toroidal angle is anti/counter-clockwise from the negative X-axis (so $\pi$ rotated from the usual sense), so that $0\degree$ is straight into the plasma, and positive `toroidal_launch_angle_TORBEAM` points in the negative Y direction.

I'm not sure about the poloidal launch angle though -- it seems that Scotty has positive $\varphi_p$ in the negative Z direction, but [TORBEAM](https://www.sciencedirect.com/science/article/pii/S0010465501001461) Fig 2a has it in the opposite sense, so that `poloidal_launch_angle_TORBEAM = 90` would point straight down in Scotty and straight up in TORBEAM.

However, the TORBEAM paper says Fig 2a has $\varphi = 20$ and the resulting beam points up, while for Fig 4 the beam also points up and the input file in the appendix has `xphdeg = -14.6`, so that's really not very clear.

**Comment by valerian-chen** [comment]
[input-output.pdf](https://github.com/beam-tracing/Scotty/files/10210782/input-output.pdf)

I've followed the sign convention at the bottom of page 3.

**Comment by ZedThree** [comment]
Ah, lovely, thanks! So the angles are more like the angles _to_ the antenna, rather than _from_ the antenna?

**Comment by valerian-chen** [comment]
Hm, I've not thought about it that way

**Comment by valerian-chen** [comment]
The PDF I uploaded should address launch angle conventions for anyone in the future looking back at this thread.
