### ISSUE TITLE
Generalize BC(s) for finite-density plasma entry

### ISSUE THREAD

**Issue by quinntpratt** [beam-tracing/Scotty#79]
As per our meeting @valerian-chen, I'm opening this issue so we can keep track of progress on allowing non-zero density at the boundary. 
Cheers.

**Comment by valerian-chen** [comment]
I'm going to be working on the theory for this over the weekend.

@ZedThree, I'm thinking about your recent changes and my upcoming changes. Right now we have poloidal_flux_enter, which is the poloidal flux where we apply both the BCs and choose the location where we start the simulation (provided both flags are True). Perhaps it's time to have two different poloidal fluxes for the events, with different names?

**Comment by valerian-chen** [comment]
I've completed the theory now, will be implementing in Scotty shortly

**Comment by valerian-chen** [comment]
Implemented! Woohoo
